---
- name: Machine related stuff
  hosts: all
  tasks:
    - ansible.builtin.shell: echo -n 'Welcome!\n' > /etc/motd

    - name: Setting hostname...
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensuring fundamental packages does exist...
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl

    - name: Checking if Docker is already installed...
      ansible.builtin.shell:
        cmd: command -v docker
      register: docker_installed
      ignore_errors: yes

    - name: Installing Docker...
      ansible.builtin.shell:
        cmd: curl -fsSL https://get.docker.com | bash -
      when: docker_installed is failed

