---
- name: Setup Kubernetes cluster "the kubeadm way"
  hosts: cplanes
  tasks:
    - name: Enabling required kernel modules...
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter
        create: yes

    - name: Setting sysctl params required by setup...
      ansible.builtin.blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        create: yes

    - name: Working around kubeadm init error issue...
      # https://stackoverflow.com/a/72508122/2075507
      ansible.builtin.shell: |
        rm /etc/containerd/config.toml
        systemctl restart containerd

    - name: Creating systemd config yaml file...
      ansible.builtin.blockinfile:
        path: /tmp/kubeadm-config.yaml
        block: |
          # kubeadm-config.yaml
          kind: ClusterConfiguration
          apiVersion: kubeadm.k8s.io/v1beta3
          kubernetesVersion: v1.25.2
          ---
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          cgroupDriver: systemd
        create: yes

    - name: Just do it!...
      ansible.builtin.command: kubeadm init --config /tmp/kubeadm-config.yaml

    - name: Getting join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: output
    - debug:
        var: output.stdout_lines

